org: rosborne132
app: todo-app
service: todo-app

myApp:
    component: 'serverless-next.js'
    inputs:
        region: us-west-2

database:
    component: '@serverless/aws-dynamodb'
    inputs:
        name: todo-items-prod
        region: us-west-2
        attributeDefinitions:
            - AttributeName: todoId
              AttributeType: S
        keySchema:
            - AttributeName: todoId
              KeyType: HASH
        billingMode: PROVISIONED
        TimeToLiveSpecification:
            AttributeName: ExpireAt
            Enabled: true
